CREATE DATABASE lasalle;
USE lasalle;

-- -----------------------------------------------------------
-- Creación de tablas
-- -----------------------------------------------------------
DROP TABLE IF EXISTS Usuario;
CREATE TABLE Usuario ( 
	Usuario			VARCHAR(30) NOT NULL PRIMARY KEY,
    Password     	VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Correlativo;
CREATE TABLE IF NOT EXISTS Correlativo 
(
	IdCorrelativo	INT NOT NULL PRIMARY KEY,
    Numero    		INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS Carrera;
CREATE TABLE Carrera ( 
	IdCarrera	VARCHAR(3) NOT NULL PRIMARY KEY,
    Nombre     	VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Persona;
CREATE TABLE IF NOT EXISTS Persona 
(
    DNI			VARCHAR(8) NOT NULL,
    Nombres    	VARCHAR(50) NOT NULL,
    Apellidos 	VARCHAR(50) NOT NULL,
    PRIMARY KEY (DNI)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Alumno;
CREATE TABLE IF NOT EXISTS Alumno 
(
    IdAlumno	VARCHAR(8) NOT NULL,
    DNI			VARCHAR(8) NOT NULL,
    Ciclo		VARCHAR(4) NOT NULL,
 	IdCarrera	VARCHAR(3) NOT NULL,
    PRIMARY KEY (IdAlumno),
    FOREIGN KEY (DNI) REFERENCES Persona(DNI)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (IdCarrera) REFERENCES Carrera(IdCarrera)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Comprobante;
CREATE TABLE IF NOT EXISTS Comprobante 
(
    IdComprobante	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Numero    		VARCHAR(10) NOT NULL,
    Rubro			VARCHAR(30) NOT NULL,
    DetalleRubro	VARCHAR(100) NOT NULL,
    Semestre		VARCHAR(10) NOT NULL,
    Cantidad		INT NOT NULL,
    Monto			DOUBLE NOT NULL,
    Fecha			DATE,
    DNI 			VARCHAR(8) NOT NULL,
    FOREIGN KEY (DNI) REFERENCES Alumno(DNI)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Agregar el campo "Estado (GIRADO / ANULADO)" en la tabla "Comprobante"  
ALTER TABLE Comprobante
	ADD Estado VARCHAR(8) NOT NULL DEFAULT 'GIRADO';

-- -----------------------------------------------------------
-- Inserción de datos de prueba
-- -----------------------------------------------------------

INSERT INTO Correlativo VALUES(1, 1000);

INSERT INTO Usuario VALUES('USUARIO','12345');

INSERT INTO Carrera VALUES('PA','PRODUCCION AGROPECUARIA');
INSERT INTO Carrera VALUES('CC','CONSTRUCCION CIVIL');
INSERT INTO Carrera VALUES('CI','COMPUTACION E INFORMATICA');
INSERT INTO Carrera VALUES('CO','CONTABILIDAD');
INSERT INTO Carrera VALUES('GO','GUIA OFICIAL DE TURISMO');
INSERT INTO Carrera VALUES('AH','ADMINISTRACION EN HOSTELERIA');
INSERT INTO Carrera VALUES('IA','INDUSTRIAS ALIMENTARIAS');
INSERT INTO Carrera VALUES('EI','EDUCACION INICIAL');
INSERT INTO Carrera VALUES('EIB','EDUCACION INICIAL EIB');
INSERT INTO Carrera VALUES('EP','EDUCACION PRIMARIA');
INSERT INTO Carrera VALUES('EF','EDUCACION FISICA');


INSERT INTO Persona VALUES('24718851','JUAN CARLOS', 'AGRAMONTE OCHOA');
INSERT INTO Persona VALUES('24718852','RAMIRO', 'RODRIGUEZ LAZO');
INSERT INTO Persona VALUES('24718853','DENNYS', 'PALOMINO GONZALES');
INSERT INTO Persona VALUES('24718854','JOSE MAURO', 'PILLCO QUISPE');
INSERT INTO Persona VALUES('24718855','HERNAN', 'CASTAÑEDA CHIRINOS');
INSERT INTO Persona VALUES('24718856','LUIS ALVARO', 'MONZON CONDORI');

INSERT INTO Alumno VALUES('ALUM0001','24718851', 'I', 'PA');
INSERT INTO Alumno VALUES('ALUM0002','24718852', 'II', 'CI');
